# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My Blog
email: michaelfbryan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    A place to write down interesting stuff I do, projects I work on, and 
    useful code snippets so I can refer to them later on.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://michaelfbryan.com" # the base hostname & protocol for your site
github_username:  Michael-F-Bryan

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
kramdown:
  input: GFM

paginate: 5
paginate_path: "/posts/page:num/"

# Include everything in the _pages directory
include: ["_pages"] 

# Make all links just use the page/post's title
permalink: /:title/ 

gems: ["jekyll-paginate"]
